### PR TITLE
Support tvOS, visionOS and macOS platform examples

### PR DESCRIPTION
**Pull request by bauer-andreas**
# Support tvOS, visionOS and macOS platform examples

## :recycle: Current situation & Problem
This PR adds tvOS, visionOS and macOS to the CI setup and project configuration to demonstrate a holistic setup.

## :gear: Release Notes 
* Added tvOS, visionOS and macOS platform. 

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by bauer-andreas** [comment]
Not sure why the visionOS UI tests are not running here. The log doesn't really give a clue.

**Review by PSchmiedmayer — APPROVED** [review]
Thank you for adding all the additional support, amazing!

**Comment by bauer-andreas** [comment]
Have we ever managed to run visionOS UI tests on GitHub Mac runners? Seems like that is an issue here(?).

**Comment by PSchmiedmayer** [comment]
@Supereg I think the issue we are encountering is related to this one: https://github.com/actions/runner-images/issues/8144#issuecomment-1902072070.

I remember that I once moved some builds to our hosted runners because the GitHub Runner performance was so slow.

Might be worth to move all of them to GitHub runners now that the macOS 14 runners are all ARM runners.

Regarding visionOS: If https://github.com/actions/runner-images/issues/8144#issuecomment-1902072070 indeed solves our problem we might want to add an additional "Setup Task" script argument to our XcodeBuild Reusable Workflow that could perform stuff like this (or any other escape hatches) before running any build? Or we just put visionOS as a custom command and run xcodebuild ourselves ...

**Comment by PSchmiedmayer** [comment]
This might be related to the issue we are having here: https://github.com/actions/runner-images/issues/9511

**Pull request merged**
